package com.demo.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("account", "id", Account.class);
		// Composite Primary Key order: accountId,roleId
		arp.addMapping("account_role", "accountId,roleId", AccountRole.class);
		arp.addMapping("blog", "id", Blog.class);
		arp.addMapping("download_log", "id", DownloadLog.class);
		arp.addMapping("permission", "id", Permission.class);
		arp.addMapping("role", "id", Role.class);
		// Composite Primary Key order: permissionId,roleId
		arp.addMapping("role_permission", "permissionId,roleId", RolePermission.class);
		arp.addMapping("session", "id", Session.class);
		arp.addMapping("upload_counter", "uploadType", UploadCounter.class);
		arp.addMapping("user", "id", User.class);
		arp.addMapping("video", "id", Video.class);
	}
}

