package com.demo.common.model;

import com.demo.common.model.base.BaseUploadCounter;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UploadCounter extends BaseUploadCounter<UploadCounter> {
	
}
